//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adc_plan_wise_benefits
    {
        public int id { get; set; }
        public string benefit_type_code { get; set; }
        public string org_code { get; set; }
        public string plan_code { get; set; }
        public Nullable<decimal> death { get; set; }
        public Nullable<decimal> hospitalization { get; set; }
        public Nullable<decimal> covid_19 { get; set; }
        public Nullable<decimal> opd { get; set; }
        public Nullable<decimal> ci { get; set; }
        public Nullable<decimal> daily_hospitalization_limit { get; set; }
        public Nullable<decimal> opd_per_visit { get; set; }
        public Nullable<decimal> per_instance_limit_for_covid_19 { get; set; }
        public string ipd_staying_limit { get; set; }
        public string hos_claim_to_claim_dis { get; set; }
        public string opd_claim_to_claim_dis { get; set; }
        public Nullable<decimal> other_limit { get; set; }
        public string remarks { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
