//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adc_claims
    {
        public int claims_id { get; set; }
        public string claim_no { get; set; }
        public string member_id { get; set; }
        public string org_code { get; set; }
        public string claim_type { get; set; }
        public string claim_option { get; set; }
        public Nullable<decimal> claimed_amount { get; set; }
        public string nid { get; set; }
        public Nullable<System.DateTime> date_of_admission { get; set; }
        public Nullable<System.DateTime> date_of_discharge { get; set; }
        public Nullable<System.DateTime> date_of_incidence { get; set; }
        public Nullable<System.DateTime> submission_date { get; set; }
        public Nullable<decimal> payable_amount { get; set; }
        public string account_type { get; set; }
        public string adc_payment_number { get; set; }
        public string remark { get; set; }
        public Nullable<int> status { get; set; }
        public string entry_user_id { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string update_user_id { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
