//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adc_member_information
    {
        public int member_info_id { get; set; }
        public string organization_code { get; set; }
        public string member_id { get; set; }
        public string member_name { get; set; }
        public string member_dob { get; set; }
        public string member_nid { get; set; }
        public string member_sex { get; set; }
        public string mobile_no { get; set; }
        public string membership_date { get; set; }
        public string comm_date { get; set; }
        public string membership_status { get; set; }
        public Nullable<decimal> sum_assured { get; set; }
        public Nullable<decimal> ci_sum_assured { get; set; }
        public string member_plan { get; set; }
        public string entry_user_id { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string update_user_id { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
