//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class astha_bahumatrik_surokkha_rate_chart
    {
        public int id { get; set; }
        public Nullable<int> plan_code { get; set; }
        public Nullable<int> min_age { get; set; }
        public Nullable<int> max_age { get; set; }
        public Nullable<int> term { get; set; }
        public Nullable<decimal> premium { get; set; }
    }
}
