//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class astha_bahumatrik_collection_main
    {
        public int id { get; set; }
        public string policy_no { get; set; }
        public Nullable<int> pr_no { get; set; }
        public Nullable<System.DateTime> pr_date { get; set; }
        public string pr_type { get; set; }
        public Nullable<int> payment_type { get; set; }
        public string mbank_ref_no { get; set; }
        public string cq_or_eft_no { get; set; }
        public string bank_name { get; set; }
        public string branch_name { get; set; }
        public Nullable<decimal> premium { get; set; }
        public Nullable<decimal> suspanse_amt { get; set; }
        public Nullable<int> term { get; set; }
        public Nullable<int> plan_code { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string fa_code { get; set; }
        public string um_code { get; set; }
        public string bm_code { get; set; }
        public Nullable<int> last_no { get; set; }
        public Nullable<int> idra_flag { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    }
}
