//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class astha_bahumatrik_surokkha_benefits
    {
        public int id { get; set; }
        public Nullable<int> plan_code { get; set; }
        public Nullable<int> term { get; set; }
        public string benefit_name { get; set; }
        public string type { get; set; }
        public Nullable<decimal> benefit_amt { get; set; }
        public string benefit_type { get; set; }
    }
}
