//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class astha_bahumatrik_surokkha
    {
        public int id { get; set; }
        public string policy_prefix { get; set; }
        public string policy_no { get; set; }
        public Nullable<System.DateTime> policy_date { get; set; }
        public Nullable<System.DateTime> proposal_date { get; set; }
        public string client_name { get; set; }
        public string gender { get; set; }
        public string personal_id_type { get; set; }
        public string personal_id { get; set; }
        public string contact_no { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> division { get; set; }
        public Nullable<int> district { get; set; }
        public Nullable<int> thana { get; set; }
        public string address { get; set; }
        public string f_name { get; set; }
        public string m_name { get; set; }
        public string s_name { get; set; }
        public string marital_status { get; set; }
        public string occupation { get; set; }
        public string nature_business { get; set; }
        public string daily_duties { get; set; }
        public string employer { get; set; }
        public string employer_address { get; set; }
        public string religion { get; set; }
        public int plan_code { get; set; }
        public Nullable<int> term { get; set; }
        public Nullable<decimal> premium { get; set; }
        public string monthly_income { get; set; }
        public string payor_name { get; set; }
        public string rel_with_client_of_payor { get; set; }
        public string fa { get; set; }
        public string um { get; set; }
        public string bm { get; set; }
        public string status { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string client_photo_path { get; set; }
        public string client_nid_path { get; set; }
        public string client_sign { get; set; }
        public string declaration_from { get; set; }
        public string und_comments { get; set; }
        public string bank_acc_name { get; set; }
        public string bank_acc_no { get; set; }
        public string bank_name { get; set; }
        public string branch_name { get; set; }
        public string routing_no { get; set; }
        public Nullable<int> isOnline { get; set; }
        public Nullable<int> und_flag { get; set; }
        public Nullable<int> idra_flag { get; set; }
    }
}
