//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bahumatrik_commission_payment
    {
        public int id { get; set; }
        public int pr_no { get; set; }
        public Nullable<System.DateTime> pr_date { get; set; }
        public string policy_no { get; set; }
        public int term { get; set; }
        public Nullable<decimal> premium { get; set; }
        public string fa_code { get; set; }
        public Nullable<decimal> com_amt_fa { get; set; }
        public Nullable<decimal> fa_tax { get; set; }
        public Nullable<decimal> fa_payable_amt { get; set; }
        public string um_code { get; set; }
        public Nullable<decimal> com_amt_um { get; set; }
        public Nullable<decimal> um_tax { get; set; }
        public Nullable<decimal> um_payable_amt { get; set; }
        public string bm_code { get; set; }
        public Nullable<decimal> com_amt_bm { get; set; }
        public Nullable<decimal> bm_tax { get; set; }
        public Nullable<decimal> bm_payable_amt { get; set; }
        public string fa_status { get; set; }
        public string fa_remarks { get; set; }
        public string um_status { get; set; }
        public string um_remarks { get; set; }
        public string bm_status { get; set; }
        public string bm_remarks { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
