//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bahumatrik_commission_rate
    {
        public int id { get; set; }
        public Nullable<int> start_year { get; set; }
        public Nullable<int> term { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> fa { get; set; }
        public Nullable<decimal> um { get; set; }
        public Nullable<decimal> bm { get; set; }
        public Nullable<int> status { get; set; }
    }
}
