//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class claim_wise_gop_details
    {
        public int id { get; set; }
        public string gop_no { get; set; }
        public string claim_no { get; set; }
        public string charge_name { get; set; }
        public Nullable<decimal> charge_wise_claim_amount { get; set; }
        public Nullable<decimal> charge_wise_settled_amount { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    }
}
