//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gop_claim_refund_recovery
    {
        public int id { get; set; }
        public string claim_no { get; set; }
        public string gop_no { get; set; }
        public string member_id { get; set; }
        public Nullable<decimal> claimed_amount { get; set; }
        public Nullable<decimal> settled_amount { get; set; }
        public Nullable<decimal> payable_amount { get; set; }
        public Nullable<decimal> refund_recoverable_amount { get; set; }
        public Nullable<decimal> refund_recovered_amount { get; set; }
        public Nullable<System.DateTime> refund_recovered_date { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string entry_by { get; set; }
    }
}
