//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_leave_users
    {
        public int id { get; set; }
        public string staff_id { get; set; }
        public string name { get; set; }
        public string role { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string mobile { get; set; }
        public string gender { get; set; }
        public Nullable<int> designation_id { get; set; }
        public string line_man_id { get; set; }
        public Nullable<int> band_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<System.DateTime> join_date { get; set; }
        public string onProbation { get; set; }
        public string active { get; set; }
        public Nullable<System.DateTime> email_verified_at { get; set; }
        public string picture { get; set; }
        public string remember_token { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> is_mancom { get; set; }
        public string status_updated_by { get; set; }
        public Nullable<System.DateTime> status_updated_at { get; set; }
        public string seperation_reason { get; set; }
        public string ims_id { get; set; }
        public Nullable<int> role_id { get; set; }
        public int car_booking_role_id { get; set; }
    }
}
