//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_leave_types
    {
        public int id { get; set; }
        public string leave_type_name { get; set; }
        public string entitled { get; set; }
        public string leave_type_details { get; set; }
        public string leave_creator_id { get; set; }
        public Nullable<int> max_leave_in_probation { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string approval_permission { get; set; }
        public int active { get; set; }
        public string genderFilter { get; set; }
        public Nullable<int> fileMandatory { get; set; }
        public Nullable<int> individual { get; set; }
        public Nullable<int> skip_weekly_holidays { get; set; }
        public Nullable<int> skip_calendar_holidays { get; set; }
    }
}
