//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_leave_records
    {
        public int id { get; set; }
        public string leave_coordinator_id { get; set; }
        public string application_to { get; set; }
        public string applicants_id { get; set; }
        public int leave_type_id { get; set; }
        public string reason { get; set; }
        public int total_entitilement_of_the_year { get; set; }
        public int leave_taken_this_year { get; set; }
        public System.DateTime leave_start_date { get; set; }
        public System.DateTime leave_end_date { get; set; }
        public int no_of_calender_days { get; set; }
        public int remaining_leave_this_year { get; set; }
        public Nullable<int> unpaid_leave_this_year { get; set; }
        public string endrosed_by_title { get; set; }
        public string endrosed_by_staff_id { get; set; }
        public string verified_by_title { get; set; }
        public string verified_by_staff_id { get; set; }
        public string official_backup_id { get; set; }
        public Nullable<int> official_backup_accepted { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> achknowledge { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> hod_approved_date { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> coordinator_checked { get; set; }
        public Nullable<int> mail_check_box { get; set; }
        public string mail_list { get; set; }
        public string msg_to_mail { get; set; }
        public string attachment { get; set; }
        public string cancel_reason { get; set; }
        public string canceled_comment { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public Nullable<int> from_carried_leave { get; set; }
        public Nullable<int> concern_from_carry_leave { get; set; }
    }
}
