//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hr_educational_info
    {
        public int id { get; set; }
        public string emp_id { get; set; }
        public string degree_name { get; set; }
        public string passing_year { get; set; }
        public string insitute_name { get; set; }
        public string board { get; set; }
        public string cgpa { get; set; }
        public string division { get; set; }
        public string @class { get; set; }
        public string grade { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    }
}
