//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_collection_main
    {
        public int id { get; set; }
        public Nullable<int> pr_no { get; set; }
        public Nullable<System.DateTime> pr_date { get; set; }
        public string pr_year { get; set; }
        public string pr_type { get; set; }
        public Nullable<double> business_code { get; set; }
        public Nullable<double> term { get; set; }
        public Nullable<double> life_premium { get; set; }
        public Nullable<double> accident_premium { get; set; }
        public Nullable<double> oe_premium { get; set; }
        public Nullable<double> fe_premium { get; set; }
        public Nullable<double> ci_premium { get; set; }
        public Nullable<double> wp_premium { get; set; }
        public Nullable<double> tot_premium { get; set; }
        public string fa_code { get; set; }
        public string bm_code { get; set; }
        public Nullable<double> last_no { get; set; }
        public string office_code { get; set; }
        public double policy_no { get; set; }
        public Nullable<double> install_no { get; set; }
        public string prem_due_dt { get; set; }
        public string cq_no { get; set; }
        public string cq_date { get; set; }
        public string bank_code { get; set; }
        public string bank_branch_code { get; set; }
        public string mbank_refno { get; set; }
        public string mbank_pament_dt { get; set; }
        public string rrno { get; set; }
        public string payment_mode { get; set; }
        public Nullable<double> hi_premium { get; set; }
        public Nullable<double> me_premium { get; set; }
        public Nullable<double> mode_of_payment { get; set; }
        public string um_code { get; set; }
        public string fa_code_old { get; set; }
        public string um_code_old { get; set; }
        public string bm_code_old { get; set; }
        public string fa_code_new { get; set; }
        public string um_code_new { get; set; }
        public string bm_code_new { get; set; }
        public Nullable<double> idra_flag { get; set; }
        public Nullable<int> ic_flag { get; set; }
    }
}
