//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_pr_type
    {
        public int id { get; set; }
        public string pr_type { get; set; }
        public string pr_description { get; set; }
        public Nullable<System.DateTime> entry_by { get; set; }
    }
}
