//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_dep_privileged
    {
        public int dep_privilegedid { get; set; }
        public Nullable<int> dep_privileged_id { get; set; }
        public string user_id { get; set; }
        public string description { get; set; }
    }
}
