//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_equip_emi_collection
    {
        public int id { get; set; }
        public Nullable<int> allocation_id { get; set; }
        public Nullable<int> dept_id { get; set; }
        public string allocated_to { get; set; }
        public Nullable<int> product_id { get; set; }
        public string product_name { get; set; }
        public Nullable<int> emi_term { get; set; }
        public Nullable<decimal> emi_amount { get; set; }
        public Nullable<int> remaining_emi_term { get; set; }
        public Nullable<decimal> total_cost { get; set; }
        public Nullable<decimal> total_paid_amount { get; set; }
        public Nullable<decimal> remaining_amount { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    }
}
