//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_com_payment
    {
        public int id { get; set; }
        public string COM_YEAR { get; set; }
        public string COM_MONTH { get; set; }
        public string COM_CYCLE { get; set; }
        public Nullable<System.DateTime> P_FROM_DATE { get; set; }
        public Nullable<System.DateTime> P_TO_DATE { get; set; }
        public string FA_CODE { get; set; }
        public Nullable<int> TOT_PR { get; set; }
        public Nullable<decimal> LIFE_PREMIUM { get; set; }
        public Nullable<decimal> ACCIDENT_PREMIUM { get; set; }
        public Nullable<decimal> CI_PREMIUM { get; set; }
        public Nullable<decimal> WP_PREMIUM { get; set; }
        public Nullable<decimal> TOT_PREMIUM { get; set; }
        public Nullable<decimal> COM_AMT_LIFE { get; set; }
        public Nullable<decimal> COM_AMT_ACCIDENT { get; set; }
        public Nullable<decimal> COM_AMT_CI { get; set; }
        public Nullable<decimal> COM_AMT_WP { get; set; }
        public Nullable<decimal> TAX { get; set; }
        public Nullable<decimal> DEDUCTION { get; set; }
        public Nullable<decimal> RESERVE_AMT { get; set; }
        public Nullable<decimal> NET_PAYABLE { get; set; }
        public string OFFICE_CODE { get; set; }
        public string EMP_STATUS { get; set; }
        public Nullable<int> DESIG_CODE { get; set; }
        public string FLAG { get; set; }
        public Nullable<decimal> DEDUCTION_FY_AMT { get; set; }
        public string BANK_ACCTNO { get; set; }
        public Nullable<int> BANK_CODE { get; set; }
        public Nullable<int> BANK_BRANCH_CODE { get; set; }
        public Nullable<decimal> HI_PREMIUM { get; set; }
        public Nullable<decimal> COM_AMT_HI { get; set; }
        public string YEAR_MONTH { get; set; }
        public Nullable<decimal> FY_AMT_TAX { get; set; }
        public Nullable<decimal> FY_AMT_PAYABLE { get; set; }
        public Nullable<decimal> FY_AMT_INTEREST { get; set; }
        public Nullable<decimal> FY_AMT_RETURN { get; set; }
        public string USERID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
    }
}
