//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bsb_claim
    {
        public int id { get; set; }
        public string claim_no { get; set; }
        public string claim_type { get; set; }
        public Nullable<System.DateTime> claim_date { get; set; }
        public Nullable<System.DateTime> occurance_date { get; set; }
        public Nullable<System.DateTime> doc_want_date { get; set; }
        public Nullable<System.DateTime> doc_receive_date { get; set; }
        public Nullable<decimal> claim_amount { get; set; }
        public Nullable<decimal> settle_amount { get; set; }
        public Nullable<decimal> payable_amount { get; set; }
        public string org_name { get; set; }
        public string eiin { get; set; }
        public string student_id { get; set; }
        public string payment_mode { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string payment_details { get; set; }
        public string claim_status { get; set; }
        public Nullable<System.DateTime> processing_date { get; set; }
        public string dr_name { get; set; }
        public string dr_reg_no { get; set; }
        public string hospital_name { get; set; }
        public string cause_of_death { get; set; }
        public Nullable<System.DateTime> tratment_date { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
