//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_ack_d
    {
        public int id { get; set; }
        public Nullable<int> policy_no { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public string remark { get; set; }
        public string user_by { get; set; }
        public string entry_by { get; set; }
    }
}
