//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_dental_health_benefits
    {
        public int id { get; set; }
        public string category_code { get; set; }
        public string benefit_type_code { get; set; }
        public string health_benefit_type_code { get; set; }
        public string org_code { get; set; }
        public string plan_code { get; set; }
        public Nullable<decimal> dental_limit { get; set; }
        public Nullable<decimal> dental_consultancy_limit { get; set; }
        public Nullable<decimal> dental_drugs_limit { get; set; }
        public Nullable<decimal> dental_investigation_limit { get; set; }
        public Nullable<decimal> dental_root_canal_limit { get; set; }
        public Nullable<decimal> dental_scaling_limit { get; set; }
        public Nullable<decimal> dental_filling_limit { get; set; }
        public Nullable<decimal> dental_others_limit { get; set; }
        public Nullable<decimal> dental_single_member_limit { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
