//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_address
    {
        public int id { get; set; }
        public string proposal_no { get; set; }
        public string address_n { get; set; }
        public string address_nn { get; set; }
        public string division_n { get; set; }
        public string district_n { get; set; }
        public string thana_n { get; set; }
        public string address_f { get; set; }
        public string address_p { get; set; }
        public string address_pp { get; set; }
        public string division_p { get; set; }
        public string district_p { get; set; }
        public string thana_p { get; set; }
        public string entry_by { get; set; }
        public string foreign_address { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
