//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_premium
    {
        public int id { get; set; }
        public string proposal_no { get; set; }
        public string plan { get; set; }
        public decimal sum_assured { get; set; }
        public System.DateTime dob { get; set; }
        public string age { get; set; }
        public Nullable<int> term { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<int> pay_mode { get; set; }
        public Nullable<decimal> basic_premium { get; set; }
        public Nullable<decimal> monthly_penson { get; set; }
        public Nullable<int> penson_starting_age { get; set; }
        public string chk_health_insurance { get; set; }
        public string health_plan { get; set; }
        public string health_beneficiary { get; set; }
        public Nullable<decimal> hi_premium { get; set; }
        public Nullable<decimal> hi_premium_net { get; set; }
        public Nullable<decimal> hi_premium_discount { get; set; }
        public Nullable<decimal> hi_sa { get; set; }
        public string chk_critical_illness { get; set; }
        public Nullable<decimal> ci_premium { get; set; }
        public Nullable<decimal> ci_sum_assured { get; set; }
        public Nullable<decimal> ci_rate_chart { get; set; }
        public string pdab_diab { get; set; }
        public Nullable<decimal> pdab_diab_rate { get; set; }
        public Nullable<decimal> pdab_diab_premium { get; set; }
        public Nullable<decimal> oe_rate { get; set; }
        public Nullable<decimal> oe_premium { get; set; }
        public Nullable<decimal> em_rate { get; set; }
        public Nullable<decimal> em_premium { get; set; }
        public string wp_flag { get; set; }
        public Nullable<decimal> wp_rate { get; set; }
        public Nullable<decimal> wp_premium { get; set; }
        public Nullable<decimal> total_premium { get; set; }
        public Nullable<System.DateTime> child_dob { get; set; }
        public Nullable<int> child_age { get; set; }
        public Nullable<decimal> monthly_stipend { get; set; }
    }
}
