//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_policy_lapse_revive
    {
        public int id { get; set; }
        public int policy_no { get; set; }
        public Nullable<int> premium_collection_id { get; set; }
        public string col_ref_no { get; set; }
        public System.DateTime policy_date { get; set; }
        public string client_name { get; set; }
        public Nullable<decimal> sum_assured { get; set; }
        public Nullable<int> term { get; set; }
        public Nullable<int> payment_mood { get; set; }
        public Nullable<decimal> tot_premium { get; set; }
        public Nullable<int> nos_installment { get; set; }
        public Nullable<decimal> tot_paid_amt { get; set; }
        public Nullable<decimal> due_premium { get; set; }
        public Nullable<int> revive_status { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
