//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_persistent_temp_02
    {
        public string PR_NO { get; set; }
        public Nullable<System.DateTime> PR_DATE { get; set; }
        public string PR_YEAR { get; set; }
        public string PR_TYPE { get; set; }
        public Nullable<int> BUSINESS_CODE { get; set; }
        public Nullable<int> TERM { get; set; }
        public decimal LIFE_PREMIUM { get; set; }
        public Nullable<decimal> ACCIDENT_PREMIUM { get; set; }
        public Nullable<decimal> OE_PREMIUM { get; set; }
        public Nullable<decimal> FE_PREMIUM { get; set; }
        public Nullable<decimal> CI_PREMIUM { get; set; }
        public decimal TOT_PREMIUM { get; set; }
        public string FA_CODE { get; set; }
        public string BM_CODE { get; set; }
        public int LAST_NO { get; set; }
        public string OFFICE_CODE { get; set; }
        public Nullable<int> POLICY_NO { get; set; }
        public Nullable<int> INSTALL_NO { get; set; }
        public Nullable<System.DateTime> PREM_DUE_DT { get; set; }
        public string CQ_NO { get; set; }
        public Nullable<System.DateTime> CQ_DATE { get; set; }
        public string BANK_CODE { get; set; }
        public string BANK_BRANCH_CODE { get; set; }
        public string MBANK_REFNO { get; set; }
        public Nullable<System.DateTime> MBANK_PAMENT_DT { get; set; }
        public string RRNO { get; set; }
        public string PAYMENT_MODE { get; set; }
        public Nullable<decimal> HI_PREMIUM { get; set; }
        public Nullable<decimal> ME_PREMIUM { get; set; }
        public Nullable<int> MODE_OF_PAYMENT { get; set; }
        public string UM_CODE { get; set; }
        public string FA_CODE_OLD { get; set; }
        public string UM_CODE_OLD { get; set; }
        public string BM_CODE_OLD { get; set; }
        public string FA_CODE_NEW { get; set; }
        public string UM_CODE_NEW { get; set; }
        public string BM_CODE_NEW { get; set; }
        public Nullable<int> IDRA_FLAG { get; set; }
    }
}
