//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_nominee_alt_history
    {
        public int id { get; set; }
        public Nullable<int> pid { get; set; }
        public string proposal_no { get; set; }
        public string nominee_type { get; set; }
        public string nominee_name { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<int> age { get; set; }
        public string relation { get; set; }
        public string share_pct { get; set; }
        public string gurdian_name { get; set; }
        public Nullable<int> guardian_age { get; set; }
        public string guardian_relation { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string policy_no { get; set; }
        public string status { get; set; }
    }
}
