//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_office_info
    {
        public int id { get; set; }
        public string office_code { get; set; }
        public string office_name { get; set; }
        public string office_address { get; set; }
        public Nullable<double> office_type { get; set; }
        public string contact_no { get; set; }
        public string fax { get; set; }
        public Nullable<double> division_code { get; set; }
        public Nullable<double> district_code { get; set; }
        public Nullable<double> thana_code { get; set; }
        public Nullable<System.DateTime> open_date { get; set; }
        public Nullable<System.DateTime> close_date { get; set; }
        public string office_status { get; set; }
        public string rent_status { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    }
}
