//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_claim_suplimentary_master
    {
        public int id { get; set; }
        public string suplimentary_id { get; set; }
        public string claim_id { get; set; }
        public Nullable<decimal> sup_amount { get; set; }
        public Nullable<System.DateTime> sup_pay_date { get; set; }
        public string sup_user { get; set; }
        public string sup_remarks { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
