//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_userid_info
    {
        public int id { get; set; }
        public string USERID { get; set; }
        public string USER_PASSWORD { get; set; }
        public string USER_STATUS { get; set; }
        public string OTP { get; set; }
        public string type { get; set; }
    }
}
