//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_benefit_types
    {
        public int id { get; set; }
        public string category_code { get; set; }
        public string benefit_type_code { get; set; }
        public string benefit_type_name { get; set; }
    }
}
