//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hr_emp_info
    {
        public int id { get; set; }
        public string emp_id { get; set; }
        public string name { get; set; }
        public string f_name { get; set; }
        public string m_name { get; set; }
        public string dept_id { get; set; }
        public string designation_id { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public string blood_group { get; set; }
        public string religion { get; set; }
        public string marital_status { get; set; }
        public string s_name { get; set; }
        public string s_mobile { get; set; }
        public string nid { get; set; }
        public string birth_certificate { get; set; }
        public string passport { get; set; }
        public string tin { get; set; }
        public string personal_number { get; set; }
        public string official_number { get; set; }
        public string personal_email { get; set; }
        public string official_email { get; set; }
        public string grade { get; set; }
        public Nullable<System.DateTime> probation_start { get; set; }
        public Nullable<System.DateTime> probation_end { get; set; }
        public Nullable<int> probation_period { get; set; }
        public Nullable<System.DateTime> confirmation_date { get; set; }
        public string salary { get; set; }
        public string img_path { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    }
}
