//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_profile
    {
        public int id { get; set; }
        public string proposal_no { get; set; }
        public string form_no { get; set; }
        public string proposal_date { get; set; }
        public string client_name { get; set; }
        public string f_name { get; set; }
        public string m_name { get; set; }
        public string s_name { get; set; }
        public string marital_status { get; set; }
        public string contact_no { get; set; }
        public string contact_no_other { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public string pregnancy { get; set; }
        public Nullable<int> month_of_pregnancy { get; set; }
        public string religion { get; set; }
        public string blood_group { get; set; }
        public string age_proof { get; set; }
        public string age_proof_code { get; set; }
        public string occupation { get; set; }
        public string main_occupation { get; set; }
        public string business_address { get; set; }
        public string annual_income { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> online_offline { get; set; }
        public string policy_option { get; set; }
        public string medical { get; set; }
        public string standard_status { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<System.DateTime> proposal_date_1 { get; set; }
        public Nullable<System.DateTime> und_recv_date { get; set; }
    }
}
