//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_plan_benefits
    {
        public int id { get; set; }
        public string plan_code { get; set; }
        public string plan_name { get; set; }
        public string maturity_facility { get; set; }
        public string partial_maturity_facility { get; set; }
        public string death_benefit { get; set; }
        public string premium_method { get; set; }
        public string others { get; set; }
        public string remarks { get; set; }
    }
}
