//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_plan
    {
        public int id { get; set; }
        public string plan_code { get; set; }
        public string org_code { get; set; }
        public string plan_no { get; set; }
        public string plan_name { get; set; }
        public Nullable<int> starting_age { get; set; }
        public Nullable<int> maximum_age { get; set; }
        public Nullable<int> child_exception_age { get; set; }
        public Nullable<int> maternity_age_limit { get; set; }
        public Nullable<int> maternity_exception_age { get; set; }
        public string remarks { get; set; }
        public string benefit_for { get; set; }
        public Nullable<int> family_plotter_flag { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
