//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_child_care_benefits
    {
        public int id { get; set; }
        public string plan_code { get; set; }
        public string plan_name { get; set; }
        public string type_code { get; set; }
        public string type_name { get; set; }
        public string age_limit_percentage { get; set; }
        public string benefits { get; set; }
    }
}
