//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_producer_attachment_dettachment
    {
        public int id { get; set; }
        public string emp_id { get; set; }
        public Nullable<double> desig_code { get; set; }
        public Nullable<System.DateTime> issue_date { get; set; }
        public string previous_chain_code { get; set; }
        public string new_chain_code { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string previous_officecode { get; set; }
        public string new_officecode { get; set; }
    }
}
