//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_claim_gops
    {
        public int id { get; set; }
        public string credit_guarantee_id { get; set; }
        public string member_id { get; set; }
        public string type_of_claim { get; set; }
        public string hospital_code { get; set; }
        public string type_of_treatement { get; set; }
        public string diagnosis { get; set; }
        public Nullable<System.DateTime> date_of_addmission { get; set; }
        public string physician_name { get; set; }
        public string ward_cabin_no { get; set; }
        public string non_payable { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string updated_by { get; set; }
    }
}
