//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_com_fy_return_temp_2
    {
        public int id { get; set; }
        public string DEV_CODE { get; set; }
        public Nullable<decimal> FY_AMT_TAX { get; set; }
        public Nullable<decimal> FY_AMT_PAYABLE { get; set; }
        public Nullable<decimal> FY_AMT_INTEREST { get; set; }
        public Nullable<decimal> FY_AMT_RETURN { get; set; }
        public string USERID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
    }
}
