//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_inv_vendor
    {
        public int id { get; set; }
        public string org_name { get; set; }
        public Nullable<int> ven_cat_id { get; set; }
        public string contact_person { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string telephone { get; set; }
        public string address { get; set; }
        public string scope_of_work { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
