//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_claims_details
    {
        public int id { get; set; }
        public string claim_no { get; set; }
        public string claim_details_id { get; set; }
        public string charge_type_code { get; set; }
        public Nullable<decimal> claimed_amount { get; set; }
        public Nullable<decimal> settled_amount { get; set; }
        public Nullable<decimal> payable_amount { get; set; }
        public Nullable<decimal> hospital_discount { get; set; }
        public Nullable<decimal> deduction_amount { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
        public string remarks { get; set; }
        public string remarks_hospital { get; set; }
        public string deduction_group_id { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
