//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_claims_idra
    {
        public int id { get; set; }
        public string claim_tracking_id { get; set; }
        public string claimNo { get; set; }
        public Nullable<System.DateTime> claimDate { get; set; }
        public string intimation_Number { get; set; }
        public Nullable<System.DateTime> intimationDate { get; set; }
        public string insuranceType { get; set; }
        public string claimType { get; set; }
        public string installmentNumber { get; set; }
        public Nullable<decimal> claimAmount { get; set; }
        public Nullable<decimal> accruedBonus { get; set; }
        public Nullable<decimal> suspense { get; set; }
        public Nullable<decimal> totalAmount { get; set; }
        public Nullable<decimal> deduction { get; set; }
        public Nullable<decimal> netPayable { get; set; }
        public string deductionCause { get; set; }
        public Nullable<decimal> reinsuranceClaimAmount { get; set; }
        public string claimStatus { get; set; }
        public string unsetteledReason { get; set; }
        public string nomineeInfo { get; set; }
        public string multiAccountPayment { get; set; }
        public string multiAccountInfo { get; set; }
        public string bankAccountName { get; set; }
        public string bankAccountNo { get; set; }
        public string bankName { get; set; }
        public string bankBranchName { get; set; }
        public string bankRoutingNo { get; set; }
        public string paymentMethod { get; set; }
        public string paymentDetail { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
        public string policyNumber { get; set; }
        public Nullable<System.DateTime> riskStartDate { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public int idra_flag { get; set; }
        public string idra_remarks { get; set; }
    }
}
