//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_info
    {
        public int id { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<int> dep_id { get; set; }
        public Nullable<int> dep_privileged_id { get; set; }
        public string isActive { get; set; }
        public string user_id { get; set; }
        public string prev_password { get; set; }
        public string user_password { get; set; }
        public Nullable<System.DateTime> password_update_date { get; set; }
        public string user_name { get; set; }
        public string name { get; set; }
        public string designation { get; set; }
        public string dep { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public Nullable<int> otp { get; set; }
        public string blood { get; set; }
        public Nullable<System.DateTime> dt_of_join { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public string updated_date { get; set; }
        public string is_password_changed { get; set; }
    }
}
