//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_maritual_status
    {
        public int maritual_status_id { get; set; }
        public string status_name { get; set; }
        public Nullable<int> active_status { get; set; }
        public string remarks { get; set; }
    }
}
