//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_com_deduction_temp
    {
        public int id { get; set; }
        public string COM_YEAR { get; set; }
        public string COM_MONTH { get; set; }
        public string COM_CYCLE { get; set; }
        public Nullable<System.DateTime> P_FROM_DATE { get; set; }
        public Nullable<System.DateTime> P_TO_DATE { get; set; }
        public string DEV_CODE { get; set; }
        public Nullable<System.DateTime> DEDUCT_DATE { get; set; }
        public Nullable<int> DEDUCTION_TYPE { get; set; }
        public Nullable<decimal> DEDUCTION_AMOUNT { get; set; }
        public string USERID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
    }
}
