//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_ssm_sm_asm
    {
        public int id { get; set; }
        public string staff_id { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<System.DateTime> doj { get; set; }
        public string designation { get; set; }
        public string id_type { get; set; }
        public string id_no { get; set; }
        public string contact_no { get; set; }
        public string email { get; set; }
        public string present_address { get; set; }
        public string parmanent_address { get; set; }
        public Nullable<int> status { get; set; }
    }
}
