//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_occupation
    {
        public int id { get; set; }
        public string sub_occupation_name { get; set; }
        public Nullable<int> @class { get; set; }
        public Nullable<int> pdab { get; set; }
        public Nullable<int> diab { get; set; }
        public Nullable<int> o_e { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    }
}
