//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_re_ins_ci_rate
    {
        public int id { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<double> premium_rate { get; set; }
        public string gender { get; set; }
    }
}
