//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_deed_delevery_details
    {
        public int id { get; set; }
        public Nullable<int> policy_no { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> deed_print_date { get; set; }
        public Nullable<System.DateTime> deed_delivery_date { get; set; }
        public Nullable<System.DateTime> ack_recive_date { get; set; }
        public string remark { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
