//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hr_emp_prev_experience
    {
        public int id { get; set; }
        public string emp_id { get; set; }
        public string company_name { get; set; }
        public string designation { get; set; }
        public string address { get; set; }
        public string job_nature { get; set; }
        public Nullable<System.DateTime> starting_date { get; set; }
        public Nullable<System.DateTime> ending_date { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    }
}
