//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_memberwise_premium_info
    {
        public int id { get; set; }
        public Nullable<int> member_info_id { get; set; }
        public string member_id { get; set; }
        public string org_code { get; set; }
        public Nullable<decimal> opd_premium { get; set; }
        public Nullable<decimal> dental_premium { get; set; }
        public Nullable<decimal> optical_premium { get; set; }
        public Nullable<decimal> ipd_premium { get; set; }
        public Nullable<decimal> maternity_premium { get; set; }
        public Nullable<decimal> supplimentary_premium { get; set; }
        public Nullable<decimal> life_premium { get; set; }
        public Nullable<decimal> ci_premium { get; set; }
        public Nullable<decimal> other_premium { get; set; }
        public Nullable<decimal> total_premium { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
