//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_claims
    {
        public int id { get; set; }
        public string claim_no { get; set; }
        public string project_code { get; set; }
        public string claim_category_code { get; set; }
        public string claim_type_code { get; set; }
        public Nullable<System.DateTime> claim_date { get; set; }
        public string dispatch_no { get; set; }
        public Nullable<System.DateTime> dispatch_date { get; set; }
        public string document_want_reason { get; set; }
        public Nullable<System.DateTime> document_want_date { get; set; }
        public string org_code { get; set; }
        public string member_id { get; set; }
        public string plan_code { get; set; }
        public string policy_id { get; set; }
        public Nullable<System.DateTime> treatment_date { get; set; }
        public Nullable<System.DateTime> date_of_addmission { get; set; }
        public Nullable<System.DateTime> date_of_discharge { get; set; }
        public Nullable<System.DateTime> document_received_date { get; set; }
        public string diagnosis { get; set; }
        public string treatment_name { get; set; }
        public string surgery_name { get; set; }
        public string consultant_type_code { get; set; }
        public string consultant_name { get; set; }
        public Nullable<decimal> claimed_amount { get; set; }
        public Nullable<decimal> settled_amount { get; set; }
        public Nullable<decimal> payable_amount { get; set; }
        public string claim_status { get; set; }
        public Nullable<System.DateTime> claim_processing_date { get; set; }
        public string hospital_code { get; set; }
        public string hospital_name { get; set; }
        public Nullable<decimal> paid_by_patient { get; set; }
        public string employee_id { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public Nullable<int> payable_to { get; set; }
        public string credit_guarantee_id { get; set; }
        public string reject_reason { get; set; }
        public string special_note { get; set; }
        public string assaigned_employee_id { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public string payment_method { get; set; }
        public string payment_detail { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<int> idra_flag { get; set; }
    }
}
