//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_wp_rate
    {
        public int id { get; set; }
        public Nullable<int> age_from { get; set; }
        public Nullable<int> age_to { get; set; }
        public Nullable<decimal> annual_premium { get; set; }
    }
}
