//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_examination_list
    {
        public int id { get; set; }
        public string code { get; set; }
        public string exam_name { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    }
}
