//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_planwise_SB_benefits
    {
        public int id { get; set; }
        public string plan_code { get; set; }
        public string installment_no { get; set; }
        public Nullable<decimal> duration_factor { get; set; }
        public Nullable<int> percentage_of_sa { get; set; }
    }
}
