//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_claim_stipend_closing_info
    {
        public int id { get; set; }
        public string claim_no { get; set; }
        public string policy_no { get; set; }
        public Nullable<System.DateTime> claim_date { get; set; }
        public Nullable<System.DateTime> stipend_closing_date { get; set; }
        public string death_of_person { get; set; }
        public string cause_of_death { get; set; }
        public Nullable<System.DateTime> occurance_date { get; set; }
        public string place_of_death { get; set; }
        public Nullable<decimal> settled_amount { get; set; }
        public string physician_name { get; set; }
        public string physician_reg_no { get; set; }
        public string hospital_name { get; set; }
        public Nullable<decimal> sum_assured { get; set; }
        public Nullable<int> tot_month_installment_paid { get; set; }
        public Nullable<decimal> total_paid_till_death { get; set; }
        public Nullable<int> tot_month_installment_payable { get; set; }
        public Nullable<decimal> total_payable_installment { get; set; }
        public Nullable<System.DateTime> doc_rcv_date { get; set; }
        public string child_gender { get; set; }
        public string nomiee_nid { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string entry_by { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<int> idra_flag { get; set; }
    }
}
