//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_tally
    {
        public int id { get; set; }
        public string rr_no { get; set; }
        public string policy_no { get; set; }
        public string bank_acc_ledger { get; set; }
        public Nullable<int> pr_no { get; set; }
        public string proposal_no { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
