//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hr_emp_address
    {
        public int id { get; set; }
        public string emp_id { get; set; }
        public string present_address { get; set; }
        public string parmanent_village { get; set; }
        public string parmanent_po { get; set; }
        public string parmanent_pc { get; set; }
        public string parmanent_ps { get; set; }
        public string parmanent_district { get; set; }
        public string parmanent_division { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    }
}
