//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_policy_child_info
    {
        public int id { get; set; }
        public string proposal_no { get; set; }
        public string child_name { get; set; }
        public string father_name { get; set; }
        public string gaurdian_name { get; set; }
        public string relation { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<int> age { get; set; }
        public string institute_name { get; set; }
        public string institute_address { get; set; }
        public string @class { get; set; }
        public string student_id { get; set; }
        public string others_compani { get; set; }
        public string others_policy_no { get; set; }
        public string others_sa { get; set; }
        public string others_plan { get; set; }
        public string others_term { get; set; }
        public string others_remarks { get; set; }
        public string rmk { get; set; }
        public string birth_certificate { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
