//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_promoted_employee_list
    {
        public int id { get; set; }
        public string dev_code { get; set; }
        public Nullable<System.DateTime> promotion_effective_date { get; set; }
        public Nullable<int> is_first_time { get; set; }
        public string prev_desig { get; set; }
        public string promoted_desig { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string entry_by { get; set; }
    }
}
