//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ocs_claim_attachment
    {
        public int id { get; set; }
        public string policy_or_member_id { get; set; }
        public Nullable<int> claim_serial_no { get; set; }
        public string claim_no { get; set; }
        public string report_name { get; set; }
        public string doc_path { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    }
}
