//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_lpb_schedule
    {
        public int SL_NO { get; set; }
        public string SCHEDULE_YEAR { get; set; }
        public Nullable<int> DEV_DESIG { get; set; }
        public Nullable<decimal> PREMIUM_MIN { get; set; }
        public Nullable<decimal> PREMIUM_MAX { get; set; }
        public Nullable<int> NOS_POLICY_NEW { get; set; }
        public Nullable<decimal> REWARD_AMT { get; set; }
        public string BUSINESS_CYCLE { get; set; }
        public string CRITERIA { get; set; }
        public Nullable<decimal> PREMIUM_NEW_FA_MIN { get; set; }
        public Nullable<decimal> PREMIUM_NEW_FA_MAX { get; set; }
        public Nullable<int> FA_RECRUITMENT { get; set; }
        public Nullable<decimal> REWARD_AMT_NEW_FA { get; set; }
    }
}
