//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hr_trainning_info
    {
        public int id { get; set; }
        public string emp_id { get; set; }
        public string trainning_title { get; set; }
        public string description { get; set; }
        public string institute_name { get; set; }
        public string flag { get; set; }
        public string term { get; set; }
        public Nullable<System.DateTime> date_from { get; set; }
        public Nullable<System.DateTime> date_to { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    }
}
