//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_organization_booking
    {
        public int id { get; set; }
        public string org_booking_code { get; set; }
        public string org_name { get; set; }
        public Nullable<int> health_status { get; set; }
        public Nullable<System.DateTime> approximate_contract_date { get; set; }
        public Nullable<int> contract_status { get; set; }
        public Nullable<System.DateTime> contract_date { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string updated_by { get; set; }
    }
}
