//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hospital_banks
    {
        public int id { get; set; }
        public string hospital_code { get; set; }
        public string bank_name { get; set; }
        public string routing_no { get; set; }
        public string branch_name { get; set; }
        public string account_no { get; set; }
        public string account_name { get; set; }
        public byte[] active_status { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string updated_by { get; set; }
    }
}
