//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_inv_transmission
    {
        public int id { get; set; }
        public string transmission_to_emp_id { get; set; }
        public Nullable<int> req_id { get; set; }
        public string sku { get; set; }
        public Nullable<int> catagory { get; set; }
        public Nullable<int> sub_catagory_id { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string transmission_reson { get; set; }
        public string product_id { get; set; }
        public string sold_id { get; set; }
        public Nullable<System.DateTime> transmission_date { get; set; }
        public string remark { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
