//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_policy_comment
    {
        public int id { get; set; }
        public string policy_no { get; set; }
        public string u_comment { get; set; }
        public string m_comment { get; set; }
        public string und_comment { get; set; }
        public string u_status { get; set; }
        public string bm_comment { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public string updated_date { get; set; }
    }
}
