//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_org_admin
    {
        public int id { get; set; }
        public string org_code { get; set; }
        public string member_id { get; set; }
        public string emp_id { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
    }
}
