//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_hi_planwise_benefits
    {
        public int id { get; set; }
        public string category_code { get; set; }
        public string plan_code { get; set; }
        public Nullable<decimal> ipd_limit { get; set; }
        public Nullable<decimal> ipd_limit_without_room_rent { get; set; }
        public Nullable<decimal> room_rent_limit { get; set; }
        public Nullable<decimal> room_rent_limit_per_day { get; set; }
        public Nullable<decimal> room_staying_limit { get; set; }
        public Nullable<decimal> icu_rent_limit { get; set; }
        public Nullable<decimal> icu_staying_limit { get; set; }
        public Nullable<decimal> ipd_consultancy_limit { get; set; }
        public Nullable<decimal> ipd_per_consultancy_max_limit { get; set; }
        public Nullable<decimal> ipd_surgery_limit { get; set; }
        public Nullable<decimal> ipd_investigation_limit { get; set; }
        public Nullable<decimal> ipd_drugs_limit { get; set; }
        public Nullable<decimal> ipd_ancillary_limit { get; set; }
        public Nullable<decimal> ipd_daily_allowances_for_gvt { get; set; }
        public Nullable<decimal> ipd_ambulance_charges_limit { get; set; }
        public Nullable<decimal> ipd_ambulance_charges_limit_max { get; set; }
        public Nullable<decimal> ipd_others { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string updated_by { get; set; }
    }
}
