//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_group_member_bank_info_update_log
    {
        public int id { get; set; }
        public string member_id { get; set; }
        public string org_code { get; set; }
        public string member_bank_name { get; set; }
        public string ac_no { get; set; }
        public string ac_name { get; set; }
        public string branch_name { get; set; }
        public string routing_no { get; set; }
        public string remarks { get; set; }
        public string updated_by { get; set; }
        public string updated_date { get; set; }
    }
}
