//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_life_benefits
    {
        public int id { get; set; }
        public string category_code { get; set; }
        public string benefit_type_code { get; set; }
        public string org_code { get; set; }
        public string plan_code { get; set; }
        public Nullable<decimal> life_benefit { get; set; }
        public Nullable<decimal> adb_benefit { get; set; }
        public Nullable<int> adb_benefit_parcent { get; set; }
        public Nullable<decimal> ppd_benefit { get; set; }
        public Nullable<int> ppd_benefit_parcent { get; set; }
        public Nullable<decimal> ptd_benefit { get; set; }
        public Nullable<int> ptd_benefit_parcent { get; set; }
        public Nullable<decimal> fpi_benefit { get; set; }
        public Nullable<int> fpi_benefit_parcent { get; set; }
        public Nullable<decimal> festival_benefit { get; set; }
        public Nullable<int> festival_benefit_parcent { get; set; }
        public Nullable<decimal> others_benefit { get; set; }
        public Nullable<int> others_benefit_parcent { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
