//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_training_info
    {
        public int id { get; set; }
        public string emp_id { get; set; }
        public string trainning_code { get; set; }
        public Nullable<System.DateTime> date_from { get; set; }
        public Nullable<System.DateTime> date_to { get; set; }
        public string user_by { get; set; }
        public string entry_by { get; set; }
        public string institute_code { get; set; }
        public string empid_old { get; set; }
        public string empid__new { get; set; }
    }
}
