//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_service_call_log_ilb
    {
        public int id { get; set; }
        public int policy_no { get; set; }
        public string contact_no { get; set; }
        public string feedback_type { get; set; }
        public string producer_type { get; set; }
        public string customer_feedback { get; set; }
        public string producer_feedback { get; set; }
        public string recommendation { get; set; }
        public Nullable<int> dnd_flag { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    }
}
