//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_medical_bill_master
    {
        public int id { get; set; }
        public string bill_no { get; set; }
        public Nullable<System.DateTime> bill_date { get; set; }
        public string policy_no { get; set; }
        public string dev_code { get; set; }
        public string office_code { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> net_amount { get; set; }
        public Nullable<decimal> discount { get; set; }
        public string medical_institute { get; set; }
        public string particular { get; set; }
        public Nullable<int> status { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    }
}
