//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_com_fy_return_temp
    {
        public int id { get; set; }
        public string COM_YEAR { get; set; }
        public string COM_MONTH { get; set; }
        public string COM_CYCLE { get; set; }
        public Nullable<System.DateTime> P_FROM_DATE { get; set; }
        public Nullable<System.DateTime> P_TO_DATE { get; set; }
        public Nullable<int> POLICY_NO { get; set; }
        public string PR_NO { get; set; }
        public Nullable<System.DateTime> PR_DATE { get; set; }
        public string PR_YEAR { get; set; }
        public string PR_TYPE { get; set; }
        public Nullable<int> BUSINESS_CODE { get; set; }
        public Nullable<int> PLAN_CODE { get; set; }
        public string OFFICE_CODE { get; set; }
        public Nullable<int> TERM { get; set; }
        public Nullable<decimal> LIFE_PREMIUM { get; set; }
        public Nullable<decimal> ACCIDENT_PREMIUM { get; set; }
        public Nullable<decimal> FE_PREMIUM { get; set; }
        public Nullable<decimal> OE_PREMIUM { get; set; }
        public Nullable<decimal> CI_PREMIUM { get; set; }
        public Nullable<decimal> HI_PREMIUM { get; set; }
        public Nullable<decimal> WP_PREMIUM { get; set; }
        public Nullable<decimal> TOT_PREMIUM { get; set; }
        public string DEV_CODE { get; set; }
        public Nullable<int> DESIG_CODE { get; set; }
        public Nullable<decimal> COM_RATE_FA { get; set; }
        public Nullable<decimal> COM_RATE_BM { get; set; }
        public Nullable<decimal> COM_AMT_LIFE { get; set; }
        public Nullable<decimal> COM_AMT_ACCIDENT { get; set; }
        public Nullable<decimal> COM_AMT_CI { get; set; }
        public Nullable<decimal> COM_AMT_HI { get; set; }
        public Nullable<decimal> COM_AMT_WP { get; set; }
        public Nullable<decimal> DEDUCTION_FY_PCT { get; set; }
        public Nullable<decimal> DEDUCTION_FY_AMT { get; set; }
        public Nullable<decimal> FY_AMT_TAX { get; set; }
        public Nullable<decimal> FY_AMT_PAYABLE { get; set; }
        public Nullable<decimal> FY_AMT_INTEREST { get; set; }
        public string USERID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
    }
}
