//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_eft_deduction
    {
        public int id { get; set; }
        public int policy_no { get; set; }
        public string eft_seqno { get; set; }
        public Nullable<System.DateTime> eft_date { get; set; }
        public string bank_acctname { get; set; }
        public string bank_acctno { get; set; }
        public string bank_code { get; set; }
        public string bank_branch_code { get; set; }
        public string eft_dd { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<int> status { get; set; }
    }
}
