//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_policy_surrender_info
    {
        public int id { get; set; }
        public string policy_no { get; set; }
        public Nullable<decimal> surrender_amount { get; set; }
        public Nullable<System.DateTime> surrender_date { get; set; }
        public string approval_doc { get; set; }
        public string payment_mode { get; set; }
        public string payment_details { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string bill_ref_no { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string entry_by { get; set; }
    }
}
