//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_producer_other_payment_info_excel_duplicate_value
    {
        public int id { get; set; }
        public string producer_code { get; set; }
        public string emp_id { get; set; }
        public string desigcode { get; set; }
        public Nullable<decimal> payment_amount { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<System.DateTime> date_from { get; set; }
        public Nullable<System.DateTime> date_to { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    }
}
