//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_stamp_stock
    {
        public int id { get; set; }
        public Nullable<int> stamp_cat { get; set; }
        public Nullable<int> stamp_purchase { get; set; }
        public Nullable<int> stamp_used { get; set; }
        public Nullable<int> stamp_lost { get; set; }
        public Nullable<int> stamp_damage { get; set; }
        public Nullable<decimal> stamp_balance { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    }
}
