//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_producer_info
    {
        public int id { get; set; }
        public string empid { get; set; }
        public string name { get; set; }
        public string f_name { get; set; }
        public string m_name { get; set; }
        public string s_name { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public string bloodgroup { get; set; }
        public string marital_status { get; set; }
        public string contact_no { get; set; }
        public string contact_no_other { get; set; }
        public string maddress1 { get; set; }
        public string maddress2 { get; set; }
        public Nullable<int> mthncode { get; set; }
        public Nullable<int> mdistcode { get; set; }
        public Nullable<int> mdivcode { get; set; }
        public string paddress1 { get; set; }
        public string paddress2 { get; set; }
        public Nullable<int> pthncode { get; set; }
        public Nullable<int> pdistcode { get; set; }
        public Nullable<int> pdivcode { get; set; }
        public string personal_id { get; set; }
        public string id_type { get; set; }
        public string email { get; set; }
        public string bank_acctno { get; set; }
        public Nullable<int> bank_code { get; set; }
        public Nullable<int> bank_branch_code { get; set; }
        public string license_no { get; set; }
        public Nullable<System.DateTime> license_issuedate { get; set; }
        public Nullable<System.DateTime> license_expiredate { get; set; }
        public Nullable<System.DateTime> joiningdate { get; set; }
        public Nullable<int> desigcode { get; set; }
        public Nullable<int> officecode { get; set; }
        public string chain_code { get; set; }
        public Nullable<int> last_id { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> pid_issue_date { get; set; }
        public Nullable<System.DateTime> pid_expire_date { get; set; }
        public Nullable<decimal> reserve_balance { get; set; }
        public string status_reason { get; set; }
        public string self_code { get; set; }
        public string highest_education { get; set; }
        public string year_of_exp { get; set; }
        public string last_company_name { get; set; }
        public string previous_desig { get; set; }
        public string nominee_name { get; set; }
        public string relation { get; set; }
        public Nullable<System.DateTime> nominee_dob { get; set; }
        public string asms_bm_self_code { get; set; }
        public string bms_um_self_code { get; set; }
        public string ums_fa_self_code { get; set; }
        public string referral_code { get; set; }
        public string dev_category { get; set; }
        public string defence_category { get; set; }
        public string defence_designation { get; set; }
        public Nullable<System.DateTime> defence_retirement_date { get; set; }
        public string empid_old { get; set; }
        public string empid_new { get; set; }
        public string empid_idra { get; set; }
        public string chain_code_old { get; set; }
        public string chain_code_new { get; set; }
        public string otp { get; set; }
        public Nullable<int> temp_flag { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public string br_status { get; set; }
        public string br_status_reason { get; set; }
        public Nullable<int> payment_flag { get; set; }
    }
}
