//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_claim_payment_bill_ref_no
    {
        public int id { get; set; }
        public string claim_no { get; set; }
        public string claim_type { get; set; }
        public string pay_mode { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string payment_ref_no { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    }
}
