//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_member_information
    {
        public int member_info_id { get; set; }
        public string member_id { get; set; }
        public string contract_no { get; set; }
        public string org_name { get; set; }
        public string member_name { get; set; }
        public Nullable<System.DateTime> member_dob { get; set; }
        public Nullable<int> member_age { get; set; }
        public string member_nid { get; set; }
        public string member_sex { get; set; }
        public Nullable<int> maritual_status { get; set; }
        public string emp_id { get; set; }
        public string emp_name { get; set; }
        public string emp_mobile { get; set; }
        public string emp_email { get; set; }
        public string emp_designation { get; set; }
        public string emp_department { get; set; }
        public Nullable<decimal> emp_salary { get; set; }
        public Nullable<int> member_relation_with_emp { get; set; }
        public Nullable<System.DateTime> membership_date { get; set; }
        public Nullable<System.DateTime> comm_date { get; set; }
        public Nullable<System.DateTime> last_renewal_date { get; set; }
        public Nullable<int> membership_status { get; set; }
        public Nullable<System.DateTime> status_effective_date { get; set; }
        public Nullable<decimal> sum_assured { get; set; }
        public Nullable<decimal> ci_sum_assured { get; set; }
        public string member_bank_name { get; set; }
        public string ac_no { get; set; }
        public string ac_name { get; set; }
        public string branch_name { get; set; }
        public string routing_no { get; set; }
        public Nullable<int> member_maternity_status { get; set; }
        public string member_plan { get; set; }
        public Nullable<System.DateTime> plan_effective_date { get; set; }
        public string previous_plan { get; set; }
        public Nullable<System.DateTime> plan_change_date { get; set; }
        public string image_title { get; set; }
        public string image_path { get; set; }
        public string project_code { get; set; }
        public string project_name { get; set; }
        public string entry_user_id { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string update_user_id { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string remarks { get; set; }
    }
}
