//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bsb_nominee_details
    {
        public int id { get; set; }
        public string claim_no { get; set; }
        public string nominee_name { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string nominee_nid { get; set; }
        public string relation_with_student { get; set; }
        public string payment_mode { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string payment_details { get; set; }
        public string cheque_no { get; set; }
        public string bank_acc_name { get; set; }
        public string bank_acc_no { get; set; }
        public string bank_name { get; set; }
        public string branch_name { get; set; }
        public string routing_no { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
