//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_claim
    {
        public int id { get; set; }
        public string policy_plan_type { get; set; }
        public string claim_no { get; set; }
        public string claim_type { get; set; }
        public Nullable<System.DateTime> claim_date { get; set; }
        public string claim_option { get; set; }
        public string cause_of_death { get; set; }
        public Nullable<System.DateTime> occurance_date { get; set; }
        public string diagnosis { get; set; }
        public Nullable<System.DateTime> treatment_date { get; set; }
        public Nullable<System.DateTime> date_of_admit { get; set; }
        public Nullable<System.DateTime> date_of_discharge { get; set; }
        public Nullable<System.DateTime> hi_treatment_date { get; set; }
        public Nullable<System.DateTime> doc_want_date { get; set; }
        public Nullable<System.DateTime> doc_recieve_date { get; set; }
        public string claim_status { get; set; }
        public string remarks { get; set; }
        public Nullable<decimal> claim_amount { get; set; }
        public Nullable<decimal> settled_amount { get; set; }
        public Nullable<decimal> tot_claim_paid_amount { get; set; }
        public Nullable<decimal> re_insurance_sa { get; set; }
        public Nullable<System.DateTime> processing_date { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string physician_name { get; set; }
        public string physician_reg_no { get; set; }
        public string hospital_name { get; set; }
        public string policy_no { get; set; }
        public Nullable<System.DateTime> policy_date { get; set; }
        public string client_name { get; set; }
        public string death_of_person { get; set; }
        public Nullable<decimal> sum_assured { get; set; }
        public Nullable<int> plan_code { get; set; }
        public Nullable<int> term { get; set; }
        public Nullable<int> payment_mood { get; set; }
        public string accident_mood { get; set; }
        public Nullable<decimal> accident_amount { get; set; }
        public string wp_flag { get; set; }
        public Nullable<decimal> tot_premium { get; set; }
        public string ci_flag { get; set; }
        public Nullable<decimal> ci_sa { get; set; }
        public Nullable<int> nos_installment { get; set; }
        public Nullable<int> hi_plan { get; set; }
        public string hi_coverage { get; set; }
        public Nullable<decimal> hi_sa { get; set; }
        public Nullable<decimal> tot_paid_amt { get; set; }
        public string payment_mode { get; set; }
        public string payment_detail { get; set; }
        public string nominee_bank_name { get; set; }
        public string nominee_branch_name { get; set; }
        public string nominee_acc_name { get; set; }
        public string cheque_no { get; set; }
        public string nominee_acc_no { get; set; }
        public string routing_no { get; set; }
        public string child_sa_percentage { get; set; }
        public string nid { get; set; }
        public Nullable<decimal> accurate_bonus { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string entry_by { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<int> idra_flag { get; set; }
    }
}
