//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_rate_chart
    {
        public int id { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> term { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<int> yearly { get; set; }
        public Nullable<decimal> half_yearly { get; set; }
        public Nullable<decimal> quarterly { get; set; }
        public Nullable<int> plan_code { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<decimal> monthly { get; set; }
    }
}
