//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_promoted_emp_initial_comm_return
    {
        public int id { get; set; }
        public Nullable<System.DateTime> ic_ded_start_date { get; set; }
        public Nullable<System.DateTime> ic_ded_end_date { get; set; }
        public string dev_code { get; set; }
        public Nullable<System.DateTime> promotion_date { get; set; }
        public Nullable<decimal> ttl_deduction_amt { get; set; }
        public Nullable<decimal> final_payable { get; set; }
        public Nullable<decimal> ttl_net_payable_amt { get; set; }
        public Nullable<decimal> ttl_tax_amt { get; set; }
        public Nullable<decimal> ttl_interest_amt { get; set; }
        public Nullable<decimal> old_reserve_amt { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string remarks { get; set; }
        public string prev_desig { get; set; }
        public string promoted_desig { get; set; }
    }
}
