//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_policy_family_history
    {
        public int id { get; set; }
        public string policy_no { get; set; }
        public string f_age { get; set; }
        public string f_hc { get; set; }
        public string f_dd { get; set; }
        public string m_age { get; set; }
        public string m_hc { get; set; }
        public string m_dd { get; set; }
        public string b_qnty { get; set; }
        public string b_age { get; set; }
        public string b_hc { get; set; }
        public string b_dd { get; set; }
        public string s_qnty { get; set; }
        public string s_age { get; set; }
        public string s_hc { get; set; }
        public string s_dd { get; set; }
        public string hw_qnty { get; set; }
        public string hw_age { get; set; }
        public string hw_hc { get; set; }
        public string hw_dd { get; set; }
        public string son_qnty { get; set; }
        public string son_age { get; set; }
        public string son_hc { get; set; }
        public string son_dd { get; set; }
        public string daughter_qnty { get; set; }
        public string daughter_age { get; set; }
        public string daughter_hc { get; set; }
        public string daughter_dd { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
