//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_hi_claim
    {
        public int id { get; set; }
        public string policy_plan_type { get; set; }
        public string claim_no { get; set; }
        public string claim_type { get; set; }
        public Nullable<System.DateTime> claim_date { get; set; }
        public Nullable<decimal> claim_amount { get; set; }
        public Nullable<decimal> settled_amount { get; set; }
        public Nullable<decimal> payable_amount { get; set; }
        public string claim_status { get; set; }
        public Nullable<System.DateTime> processing_date { get; set; }
        public Nullable<int> hi_plan { get; set; }
        public Nullable<decimal> hi_prem { get; set; }
        public string hi_sa { get; set; }
        public Nullable<decimal> hi_prem_rcv { get; set; }
        public Nullable<System.DateTime> hi_due_dt { get; set; }
        public string treatment_type { get; set; }
        public string diagnosis { get; set; }
        public string surgery_name { get; set; }
        public Nullable<System.DateTime> treatment_date { get; set; }
        public Nullable<System.DateTime> date_of_admit { get; set; }
        public Nullable<System.DateTime> date_of_discharge { get; set; }
        public string staying_limit { get; set; }
        public Nullable<System.DateTime> doc_want_date { get; set; }
        public Nullable<System.DateTime> doc_recieve_date { get; set; }
        public string hospital_name { get; set; }
        public string physician_name { get; set; }
        public string physician_reg_no { get; set; }
        public string patient_name { get; set; }
        public Nullable<System.DateTime> patient_dob { get; set; }
        public string relation_with { get; set; }
        public string policy_no { get; set; }
        public string proposal_no { get; set; }
        public Nullable<decimal> sum_assured { get; set; }
        public string policy_date { get; set; }
        public string policy_status { get; set; }
        public Nullable<int> payment_mood { get; set; }
        public Nullable<decimal> tot_premium { get; set; }
        public Nullable<int> plan_code { get; set; }
        public Nullable<int> term { get; set; }
        public Nullable<System.DateTime> comm_date { get; set; }
        public Nullable<System.DateTime> date_of_maturity { get; set; }
        public string client_name { get; set; }
        public string injury_type { get; set; }
        public string remarks { get; set; }
        public Nullable<int> gvt_hospital_flat { get; set; }
        public string payment_method { get; set; }
        public string payment_detail { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string entry_by { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<int> idra_flag { get; set; }
    }
}
