//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_inv_details_test
    {
        public int id { get; set; }
        public string product_name { get; set; }
        public string sku { get; set; }
        public string barcode { get; set; }
        public string unit { get; set; }
        public Nullable<int> catagory { get; set; }
        public Nullable<int> sub_catagory_id { get; set; }
        public Nullable<decimal> item_quantity { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public string branda { get; set; }
        public string description { get; set; }
        public string warranty { get; set; }
        public string pruchase_date { get; set; }
        public string expiration_date { get; set; }
        public string vendor_name { get; set; }
        public string product_type { get; set; }
        public string product_color { get; set; }
        public string comment { get; set; }
        public string csv_number { get; set; }
        public string bill_no { get; set; }
        public Nullable<int> buffer_limit { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
