//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ocs_claim_details
    {
        public int id { get; set; }
        public string policy_or_member_id { get; set; }
        public Nullable<int> claim_serial_no { get; set; }
        public string claim_no { get; set; }
        public string hospital_accomodation_charge { get; set; }
        public string consultation_fee { get; set; }
        public string investigation_fee { get; set; }
        public string medicines_fee { get; set; }
        public string surgical_fee { get; set; }
        public string ancillary_fee { get; set; }
        public string other_fee { get; set; }
        public string discount { get; set; }
        public string total_claim_amount { get; set; }
        public string acc_name { get; set; }
        public string acc_no { get; set; }
        public string bank_name { get; set; }
        public string bank_branch { get; set; }
        public string routing_no { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<int> accept_status { get; set; }
    }
}
