//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_inv_bull_user
    {
        public int id { get; set; }
        public string emp_id { get; set; }
        public string emp_name { get; set; }
        public string emp_designation { get; set; }
        public string contact_no { get; set; }
        public string bill_no { get; set; }
        public string bill_date { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> net_amount { get; set; }
        public string referance_no { get; set; }
        public string particular { get; set; }
        public string path { get; set; }
        public string csv_number { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
