//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_prospective_group_info
    {
        public int id { get; set; }
        public string date_of_entry { get; set; }
        public string prospective_org { get; set; }
        public string mailing_address { get; set; }
        public string m_thana_code { get; set; }
        public string m_district_code { get; set; }
        public string m_div_code { get; set; }
        public string contact_person_name { get; set; }
        public string designation { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string nature_of_business { get; set; }
        public string num_of_insured_approx { get; set; }
        public string num_of_employee { get; set; }
        public string num_of_dependents { get; set; }
        public string average_age { get; set; }
        public string effecive_date_coverage { get; set; }
        public string existing_insurance_flag { get; set; }
        public string existing_insurance_cover_number { get; set; }
        public string proposed_effective_date_coverage { get; set; }
        public string basic_life_coverage_sum_assured { get; set; }
        public string adb { get; set; }
        public string aptd { get; set; }
        public string appd { get; set; }
        public string ipd_sum_assured { get; set; }
        public string maternity_sum_assured { get; set; }
        public string opd_gen_sum_assured { get; set; }
        public string opd_dental_sum_assurde { get; set; }
        public string opd_optical_sum_assued { get; set; }
        public string ci_sum_assurde { get; set; }
        public string fa_code { get; set; }
        public string um_code { get; set; }
        public string bm_code { get; set; }
        public string executive { get; set; }
        public Nullable<int> status { get; set; }
        public string entry_date { get; set; }
    }
}
