//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_organizations
    {
        public int id { get; set; }
        public string org_code { get; set; }
        public Nullable<bool> has_mother { get; set; }
        public string mother_org_code { get; set; }
        public string org_name { get; set; }
        public string org_address { get; set; }
        public Nullable<int> payable_to_id { get; set; }
        public string org_phone { get; set; }
        public string org_email { get; set; }
        public Nullable<System.DateTime> contract_date { get; set; }
        public Nullable<int> contract_term { get; set; }
        public Nullable<System.DateTime> commencement_date { get; set; }
        public Nullable<decimal> profit_commission { get; set; }
        public Nullable<decimal> management_expenses { get; set; }
        public Nullable<System.DateTime> org_renewal_date { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<int> health_status { get; set; }
        public Nullable<int> org_status { get; set; }
        public Nullable<bool> co_insurance_status { get; set; }
        public Nullable<int> co_insurance_percentage { get; set; }
        public Nullable<int> disability_flag { get; set; }
        public string marketed_by { get; set; }
        public string offered_by_main { get; set; }
        public string fa_code { get; set; }
        public string fa_name { get; set; }
        public string group_dep_emp { get; set; }
        public string referred_by_main { get; set; }
        public string emp_id { get; set; }
        public string name_other { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string updated_by { get; set; }
    }
}
