//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_sms_policy
    {
        public int id { get; set; }
        public Nullable<int> policy_no { get; set; }
        public Nullable<System.DateTime> prem_due_date { get; set; }
        public Nullable<int> prem_due_date_flag { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<int> dob_flag { get; set; }
        public Nullable<int> policy_issue_flag { get; set; }
        public Nullable<System.DateTime> child_dob { get; set; }
        public Nullable<int> child_dob_flag { get; set; }
    }
}
