//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_policy_info
    {
        public int id { get; set; }
        public Nullable<int> policy_no { get; set; }
        public Nullable<System.DateTime> policy_date { get; set; }
        public string client_name { get; set; }
        public string f_name { get; set; }
        public string m_name { get; set; }
        public string s_name { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public string religion { get; set; }
        public string marital_status { get; set; }
        public string blood_group { get; set; }
        public string contact_no { get; set; }
        public string contact_no_other { get; set; }
        public string email_id { get; set; }
        public string nid { get; set; }
        public string maddress1 { get; set; }
        public string maddress2 { get; set; }
        public Nullable<int> mthncode { get; set; }
        public Nullable<int> mdistcode { get; set; }
        public Nullable<int> mdivcode { get; set; }
        public string paddress1 { get; set; }
        public string paddress2 { get; set; }
        public Nullable<int> pthcode { get; set; }
        public Nullable<int> pdistcode { get; set; }
        public Nullable<int> pdivcode { get; set; }
        public Nullable<int> office_code { get; set; }
        public Nullable<System.DateTime> comm_date { get; set; }
        public Nullable<System.DateTime> risk_date { get; set; }
        public Nullable<int> occupation_code { get; set; }
        public string age_proofcode { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<decimal> sum_assured { get; set; }
        public Nullable<int> plan_code { get; set; }
        public Nullable<int> term { get; set; }
        public Nullable<decimal> premium_rate { get; set; }
        public Nullable<int> payment_mood { get; set; }
        public Nullable<decimal> payment_mood_rate { get; set; }
        public Nullable<decimal> life_premium { get; set; }
        public string accident_mood { get; set; }
        public Nullable<decimal> accident_rate { get; set; }
        public Nullable<decimal> accident_amount { get; set; }
        public string class_mode { get; set; }
        public string o_e_mood { get; set; }
        public Nullable<decimal> o_e_rate { get; set; }
        public Nullable<decimal> o_e_amount { get; set; }
        public string f_e_mode { get; set; }
        public Nullable<decimal> f_e_rate { get; set; }
        public Nullable<decimal> f_e_amount { get; set; }
        public string wp_flag { get; set; }
        public Nullable<decimal> wp_rate { get; set; }
        public Nullable<decimal> wp_premium { get; set; }
        public Nullable<decimal> tot_premium { get; set; }
        public string medical { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string fa { get; set; }
        public string um { get; set; }
        public string bm { get; set; }
        public string minority { get; set; }
        public string pregnancy { get; set; }
        public string option_type { get; set; }
        public string standard_status { get; set; }
        public string child_name { get; set; }
        public Nullable<System.DateTime> child_dob { get; set; }
        public string child_age { get; set; }
        public string child_birth_certificate { get; set; }
        public string policy_status { get; set; }
        public string bank_acctno { get; set; }
        public string bank_code { get; set; }
        public string bank_branch_code { get; set; }
        public Nullable<decimal> fpr_amount { get; set; }
        public Nullable<System.DateTime> proposal_date { get; set; }
        public Nullable<int> pension_start_age { get; set; }
        public Nullable<int> monthly_pension { get; set; }
        public Nullable<decimal> rate_code { get; set; }
        public string ci_flag { get; set; }
        public Nullable<decimal> ci_rate { get; set; }
        public Nullable<decimal> ci_premium { get; set; }
        public Nullable<int> nos_installment { get; set; }
        public Nullable<System.DateTime> next_prem_date { get; set; }
        public Nullable<decimal> ci_sa { get; set; }
        public Nullable<decimal> suspense_amt { get; set; }
        public Nullable<decimal> stamp_amt { get; set; }
        public string me_mode { get; set; }
        public Nullable<decimal> me_rate { get; set; }
        public Nullable<decimal> me_amount { get; set; }
        public string smoking_flag { get; set; }
        public string hi_flag { get; set; }
        public Nullable<int> hi_plan { get; set; }
        public string hi_coverage { get; set; }
        public Nullable<decimal> hi_prem_discount { get; set; }
        public Nullable<decimal> hi_premium_total { get; set; }
        public Nullable<decimal> hi_premium_net { get; set; }
        public Nullable<System.DateTime> hi_due_dt { get; set; }
        public string eft_flag { get; set; }
        public string bank_aactname { get; set; }
        public string ack_deliver { get; set; }
        public string ack_receive { get; set; }
        public Nullable<decimal> tot_paid_amt { get; set; }
        public Nullable<decimal> hi_sa { get; set; }
        public Nullable<int> eft_dd { get; set; }
        public string fa_old { get; set; }
        public string um_old { get; set; }
        public string bm_old { get; set; }
        public string fa_new { get; set; }
        public string um_new { get; set; }
        public string bm_new { get; set; }
        public string proposal_no { get; set; }
        public Nullable<int> idra_flag { get; set; }
        public Nullable<int> dnd_flag { get; set; }
    }
}
