//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bsb_claim_student_payment_schedule
    {
        public int id { get; set; }
        public string claim_no { get; set; }
        public string payment_date { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string installment_no { get; set; }
        public string flag { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<int> idra_flag { get; set; }
    }
}
