//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_policy_payment
    {
        public int id { get; set; }
        public string policy_no { get; set; }
        public string form_no { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string payment_type { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string transaction_id { get; set; }
        public Nullable<decimal> collected_amount { get; set; }
        public string bank_name { get; set; }
        public string doc_path { get; set; }
        public string remark { get; set; }
        public Nullable<int> Status { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
