//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ocs_claim
    {
        public int id { get; set; }
        public string policy_or_member_id { get; set; }
        public Nullable<int> claim_serial_no { get; set; }
        public string claim_no { get; set; }
        public string claim_type { get; set; }
        public string hospital_name { get; set; }
        public string hospital_address { get; set; }
        public Nullable<System.DateTime> date_of_addmission { get; set; }
        public Nullable<System.DateTime> date_of_discharge { get; set; }
        public Nullable<System.DateTime> date_of_treatment { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<int> accept_status { get; set; }
    }
}
