//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilb_hi_coverage
    {
        public int id { get; set; }
        public string form_no { get; set; }
        public string proposal_no { get; set; }
        public string policy_no { get; set; }
        public string name { get; set; }
        public string dob { get; set; }
        public Nullable<int> age { get; set; }
        public string relation { get; set; }
        public Nullable<decimal> premium { get; set; }
        public Nullable<decimal> hi_sa { get; set; }
        public string entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
