//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Third_Party_Token
    {
        public int Id { get; set; }
        public string Access_Token { get; set; }
        public string Remarks { get; set; }
        public int Status { get; set; }
    }
}
